POST http://localhost:4000/api/customers/create
Content-Type: application/json

{
    "id": "2",
    "email": "vinh@gmail.com",
    "name": "asdfasdf",
    "address": {
        "line1" : "aaa",
        "line2": "",
        "zip" : "0000",
        "city" : "ha noi",
        "state" : "viet nam "
    }
}
###
GET http://localhost:4000/api/customers

###
GET  http://localhost:4000/api/users/list

###
GET  http://localhost:4000/api/users/1



###
POST  http://localhost:4000/api/users/create
Content-Type: application/json

{
    "firstName": "Hoang Anh"
}
###
PUT  http://localhost:4000/api/users/1
Content-Type: application/json

{
    "firstName": "Hoang Anh"
}
###
DELETE http://localhost:4000/api/users/1

###
POST  http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email": "toan@gmail.com",
    "password": "password",
    "username": "Văn toán"
}

###
POST  http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "vinh@gmail.com",
    "password": "password"
}