POST  http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email": "toan@gmail.com",
    "password": "password",
    "username": "Văn toán"
}

###
POST  http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "vinh@gmail.com",
    "password": "password"
}


###
GET   http://localhost:4000/api/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhAZ21haWwuY29tIiwiaWF0IjoxNjczOTIzOTE5LCJleHAiOjE2NzM5Mjc1MTl9.y_k6ydhxm7FzJUDpkir0Wh7B-tSpvZz3m_-E9W0vJQI

{
    "email": "vinh@gmail.com"
}

###
PUT   http://localhost:4000/api/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhAZ21haWwuY29tIiwiaWF0IjoxNjc1NDE3MTI0LCJleHAiOjE2NzU0MjA3MjR9.8D1tp1dDG-wiaPSqEmc5RVw6V-RbJhws9vJ9T6nQLEI

{
    "image": "image update",
    "bio": "bio update part 2"
}

###
GET   http://localhost:4000/api/profile/vinh@gmail.com
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhAZ21haWwuY29tIiwiaWF0IjoxNjczOTIzOTE5LCJleHAiOjE2NzM5Mjc1MTl9.y_k6ydhxm7FzJUDpkir0Wh7B-tSpvZz3m_-E9W0vJQI

###
Post   http://localhost:4000/api/profile/toan@gmail.com/follow
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhAZ21haWwuY29tIiwiaWF0IjoxNjc1NDE3MTI0LCJleHAiOjE2NzU0MjA3MjR9.8D1tp1dDG-wiaPSqEmc5RVw6V-RbJhws9vJ9T6nQLEI


###
DELETE    http://localhost:4000/api/profile/toan@gmail.com/follow
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhAZ21haWwuY29tIiwiaWF0IjoxNjczOTI3OTg1LCJleHAiOjE2NzM5MzE1ODV9.xLtkR3FSc1xAnTx1KN6iAMpS6Y2XWvIRYUi9oEPHTiI

###
POST      http://localhost:4000/api/articles
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmhAZ21haWwuY29tIiwiaWF0IjoxNjc1NDIxMTQ3LCJleHAiOjE2NzU0MjQ3NDd9.yTaScivpCrgiIsV9Q-8RsV6NfDe3kQGw-xKc6-jOwEQ

{
        "title": "this is title",
        "body": "body",
        "description": "aaa",
        "tagList": []
}
